import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Experts',
    description: 'Generated by create next app',
};

export default function Experts() {
    return <div>experts</div>;
}
